import { Injectable, Logger } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../infrastructure/prisma/prisma.service.js';

export enum EventType {
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  // Finance events
  INCOME_RECEIVED = 'INCOME_RECEIVED',
  INCOME_UPDATED = 'INCOME_UPDATED',
  INCOME_DELETED = 'INCOME_DELETED',
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_UPDATED = 'EXPENSE_UPDATED',
  EXPENSE_DELETED = 'EXPENSE_DELETED',
  BUDGET_CREATED = 'BUDGET_CREATED',
  BUDGET_UPDATED = 'BUDGET_UPDATED',
  BUDGET_DELETED = 'BUDGET_DELETED',
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  // Goal events
  GOAL_CREATED = 'GOAL_CREATED',
  GOAL_UPDATED = 'GOAL_UPDATED',
  GOAL_DELETED = 'GOAL_DELETED',
  GOAL_MILESTONE_CREATED = 'GOAL_MILESTONE_CREATED',
  GOAL_MILESTONE_UPDATED = 'GOAL_MILESTONE_UPDATED',
  GOAL_MILESTONE_DELETED = 'GOAL_MILESTONE_DELETED',
  GOAL_FORECAST_GENERATED = 'GOAL_FORECAST_GENERATED',
  // Learning events
  VOCABULARY_CREATED = 'VOCABULARY_CREATED',
  VOCABULARY_LEARNED = 'VOCABULARY_LEARNED',
  VOCABULARY_REVIEWED = 'VOCABULARY_REVIEWED',
  LEARNING_PLAN_CREATED = 'LEARNING_PLAN_CREATED',
  HSK_GOAL_CREATED = 'HSK_GOAL_CREATED',
  // Schedule events
  FIXED_EVENT_CREATED = 'FIXED_EVENT_CREATED',
  FIXED_EVENT_UPDATED = 'FIXED_EVENT_UPDATED',
  FIXED_EVENT_DELETED = 'FIXED_EVENT_DELETED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_DELETED = 'TASK_DELETED',
  TASK_OVERDUE = 'TASK_OVERDUE',
  SCHEDULE_PLAN_GENERATED = 'SCHEDULE_PLAN_GENERATED',
  // AI events
  AI_RECOMMENDATIONS_GENERATED = 'AI_RECOMMENDATIONS_GENERATED',
  AI_SUGGESTION_ACCEPTED = 'AI_SUGGESTION_ACCEPTED',
  AI_SUGGESTION_DISMISSED = 'AI_SUGGESTION_DISMISSED',
  // Notification events
  NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
  NOTIFICATION_READ = 'NOTIFICATION_READ',
  NOTIFICATION_ARCHIVED = 'NOTIFICATION_ARCHIVED',
  NOTIFICATION_PREFERENCES_UPDATED = 'NOTIFICATION_PREFERENCES_UPDATED',
  // Food events
  INGREDIENT_CREATED = 'INGREDIENT_CREATED',
  INGREDIENT_UPDATED = 'INGREDIENT_UPDATED',
  INGREDIENT_DELETED = 'INGREDIENT_DELETED',
  INGREDIENT_PURCHASED = 'INGREDIENT_PURCHASED',
  RECIPE_CREATED = 'RECIPE_CREATED',
  RECIPE_UPDATED = 'RECIPE_UPDATED',
  RECIPE_DELETED = 'RECIPE_DELETED',
  MEAL_PLAN_CREATED = 'MEAL_PLAN_CREATED',
  MEAL_PLAN_UPDATED = 'MEAL_PLAN_UPDATED',
  MEAL_PLAN_DELETED = 'MEAL_PLAN_DELETED',
  SHOPPING_LIST_CREATED = 'SHOPPING_LIST_CREATED',
  SHOPPING_LIST_UPDATED = 'SHOPPING_LIST_UPDATED',
  SHOPPING_LIST_COMPLETED = 'SHOPPING_LIST_COMPLETED',
  SHOPPING_LIST_DELETED = 'SHOPPING_LIST_DELETED',
}

export interface PublishEventDto {
  userId?: string;
  eventType: EventType | string;
  sourceModule: string;
  payload: Record<string, unknown>;
}

@Injectable()
export class EventsService {
  private readonly logger = new Logger(EventsService.name);

  constructor(private readonly prisma: PrismaService) {}

  async publish(dto: PublishEventDto): Promise<void> {
    try {
      await this.prisma.event.create({
        data: {
          userId: dto.userId,
          eventType: dto.eventType,
          sourceModule: dto.sourceModule,
          payloadJson: dto.payload as Prisma.InputJsonValue,
        },
      });
    } catch (err) {
      this.logger.error(`Failed to publish event ${dto.eventType}`, err);
    }
  }
}
